name: activity_social_app
description: A social activity management and discovery app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.15.1
  firebase_storage_web: ^3.7.0
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.7
  google_maps_flutter: ^2.5.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  image_picker: ^1.0.5
  geolocator: ^10.1.0
  timeago: ^3.6.0
  uuid: ^4.2.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  js: ^0.6.7


flutter:
  uses-material-design: true
  assets:
    - assets/images/