name: activity_social_app
description: A social activity management and discovery app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.9.4
  google_maps_flutter: ^2.10.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  cached_network_image: ^3.4.0
  intl: ^0.18.1
  image_picker: ^1.1.2
  geolocator: ^10.1.1
  timeago: ^3.7.0
  uuid: ^4.5.1
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/