// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/// Firebase 配置選項文件
/// 
/// 此文件包含所有平台的 Firebase 配置信息：
/// 1. Web 平台配置
/// 2. Android 平台配置
/// 3. iOS 平台配置
/// 4. macOS 平台配置
/// 5. Windows 平台配置
/// 
/// 注意：此文件由 FlutterFire CLI 自動生成，不建議手動修改
/// 如需更新配置，請使用 FlutterFire CLI 重新生成

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// 默認的 [FirebaseOptions] 配置類
/// 
/// 使用示例：
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// 根據當前平台返回對應的 Firebase 配置
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web 平台的 Firebase 配置
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXi4oXXMy6RIBCHRh2Han-Y0Xp_oMPBFA',
    appId: '1:107372188992:web:b4ae3a6e5b3b3cb14ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    authDomain: 'linkup-2ffac.firebaseapp.com',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
    measurementId: 'G-4BE94HSVT4',
  );

  /// Android 平台的 Firebase 配置
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRJBAo1Yjv-JqykikAIKvSY0xqTzmgXfI',
    appId: '1:107372188992:android:e386328acad764664ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
  );

  /// iOS 平台的 Firebase 配置
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7CNzLXTZ2u3TmcAog8YM4BJsWI6-0wI',
    appId: '1:107372188992:ios:f7e7f433cda3c4f94ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
    iosBundleId: 'com.example.activitySocialApp',
  );

  /// macOS 平台的 Firebase 配置
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh7CNzLXTZ2u3TmcAog8YM4BJsWI6-0wI',
    appId: '1:107372188992:ios:f7e7f433cda3c4f94ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
    iosBundleId: 'com.example.activitySocialApp',
  );

  /// Windows 平台的 Firebase 配置
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXi4oXXMy6RIBCHRh2Han-Y0Xp_oMPBFA',
    appId: '1:107372188992:web:bdc6dd0de050f8594ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    authDomain: 'linkup-2ffac.firebaseapp.com',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
    measurementId: 'G-KYLQCZBDJQ',
  );
}
