// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXi4oXXMy6RIBCHRh2Han-Y0Xp_oMPBFA',
    appId: '1:107372188992:web:b4ae3a6e5b3b3cb14ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    authDomain: 'linkup-2ffac.firebaseapp.com',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
    measurementId: 'G-4BE94HSVT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRJBAo1Yjv-JqykikAIKvSY0xqTzmgXfI',
    appId: '1:107372188992:android:e386328acad764664ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7CNzLXTZ2u3TmcAog8YM4BJsWI6-0wI',
    appId: '1:107372188992:ios:f7e7f433cda3c4f94ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
    iosBundleId: 'com.example.activitySocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh7CNzLXTZ2u3TmcAog8YM4BJsWI6-0wI',
    appId: '1:107372188992:ios:f7e7f433cda3c4f94ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
    iosBundleId: 'com.example.activitySocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXi4oXXMy6RIBCHRh2Han-Y0Xp_oMPBFA',
    appId: '1:107372188992:web:bdc6dd0de050f8594ad6a5',
    messagingSenderId: '107372188992',
    projectId: 'linkup-2ffac',
    authDomain: 'linkup-2ffac.firebaseapp.com',
    storageBucket: 'linkup-2ffac.firebasestorage.app',
    measurementId: 'G-KYLQCZBDJQ',
  );
}
